### ISSUE TITLE
Uncaught AttributeError: 'list' object has no attribute 'length'


### ISSUE THREAD

**Issue by peter-shr** [IDTruke/QGIS-Super_Copier#10]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\Super_Copier\Super_Copier.py", line 340, in run
    self.finalCopy(layer_orig, layer_dest, self.prepaData(ldest_fields))
  File "C:/Users/USER/.qgis2/python/plugins\Super_Copier\Super_Copier.py", line 247, in prepaData
    if fields.length > 0 :
AttributeError: 'list' object has no attribute 'length'

```
Super_Copier 0.1.1, QGIS 2.14.18-Essen on Windows 10

**Comment by IDTruke** [comment]
Migrate to Super_Copier 0.1.2
